### ISSUE TITLE
goformation breaks `Output`s in existing templates

### ISSUE THREAD

**Issue by stilvoid** [awslabs/goformation#144]
Given the following template:

```yaml
Resources:
  Bucket:
    Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Value: !Ref Bucket
```

and the following code:

```go
package main

import (
        "fmt"

        "github.com/awslabs/goformation"
)

func main() {
        t, _ := goformation.Open("broken.yaml")
        y, _ := t.YAML()
        fmt.Println(string(y))
}
```

You get the following output:
```yaml
Outputs:
  BucketName:
    Value: null
Resources:
  Bucket:
    Type: AWS::S3::Bucket
```

The `Value` of the `Output` has disappeared :(
