### ISSUE TITLE
IAM Policy Conditions are rendered as `['null']`

### ISSUE THREAD

**Issue by randomvariable** [awslabs/goformation#157]
In CFN, IAM Policy conditions are represented in a PolicyDocument object with a `Condition` key.

Unfortunately, GoFormation interprets this as a Condition intrinsic and attempts to process it, fails and represents the output as null.

We are [using a workaround](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/489/files#diff-dda943b09c19aedaa6401e396f3def96R67) based on string replacement, but would be good to solve properly.

**Comment by grahamjenson** [comment]
Can you give an example in YAML of the file you are trying to process. I have a PR that sounds like it is trying to solve a similar problem #158 It doe not support `Condidtion` yet though. 

Goformation can store intrinsic objects as Base64 encoded strings in the Gostruct and will decode those to the properly when using `template.JSON` or `template.YAML`. This might be helpful for a workaround.

To use the encoding intrinsics use:

```
template, err := goformation.ParseYAMLWithOptions(input, &intrinsics.ProcessorOptions{
					IntrinsicHandlerOverrides: cloudformation.EncoderIntrinsics,
				})
```

**Comment by randomvariable** [comment]
We're using the Go template, so start with an IAM policy document with the following statement:
``` go
			{
				Effect: iam.EffectAllow,
				Resource: iam.Resources{fmt.Sprintf(
					"arn:aws:iam::%s:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing",
					accountID),
				},
				Action: iam.Actions{
					"iam:CreateServiceLinkedRole",
				},
				Condition: iam.Conditions{
					"StringLike": map[string]string{"iam:AWSServiceName": "elasticloadbalancing.amazonaws.com"},
				},
			},
```

we should end up with a resultant template with the following resource:

``` yaml
  AWSIAMManagedPolicyControllers:
    Properties:
      Description: For the Kubernetes Cluster API Provider AWS Controllers
      Groups:
      - Ref: AWSIAMGroupBootstrapper
      ManagedPolicyName: controllers.cluster-api-provider-aws.sigs.k8s.io
      PolicyDocument:
        Statement:
        - Action:
          - ec2:AllocateAddress
          - elasticloadbalancing:RegisterInstancesWithLoadBalancer
          Effect: Allow
          Resource:
          - '*'
        - Action:
          - iam:CreateServiceLinkedRole
          Effect: Allow
          Condition:
            StringLike:
              iam:AWSServiceName: elasticloadbalancing.amazonaws.com
          Resource:
          - arn:aws:iam::012345678901:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing
        Version: "2012-10-17"
      Roles:
      - Ref: AWSIAMRoleControllers
      - Ref: AWSIAMRoleControlPlane
    Type: AWS::IAM::ManagedPolicy
```

but instead get:
``` yaml
  AWSIAMManagedPolicyControllers:
    Properties:
      Description: For the Kubernetes Cluster API Provider AWS Controllers
      Groups:
      - Ref: AWSIAMGroupBootstrapper
      ManagedPolicyName: controllers.cluster-api-provider-aws.sigs.k8s.io
      PolicyDocument:
        Statement:
        - Action:
          - ec2:AllocateAddress
          - elasticloadbalancing:RegisterInstancesWithLoadBalancer
          Effect: Allow
          Resource:
          - '*'
        - null
      Roles:
      - Ref: AWSIAMRoleControllers
      - Ref: AWSIAMRoleControlPlane
    Type: AWS::IAM::ManagedPolicy
```

I did try going down the `NoProcess: true` route, but ended up with Base64 encoded strings for where we're really using intrinsics with `Ref`.
