### ISSUE TITLE
Polymorphic type will hide and lose data

### ISSUE THREAD

**Issue by grahamjenson** [awslabs/goformation#171]
A template like 

```
...
Resources:
  hello:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        a:
          Type: DynamoDB
          Properties:
            StartingPosition: asd
            BatchSize: 1
            Stream: db
```

If converted to YAML and back will then look like:

```
Resources:
  hello:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        a:
          Type: DynamoDB
          Properties:
            BatchSize: 1
```

Because the polymorphic type will think it is an SQS Queue and return it. 

To "solve" this I used the heuristic the largest JSON blob is probably the correct one, so I marshal all types and sort to find the largest as seen here:
https://github.com/grahamjenson/goformation/commit/d136761d127e02f333f782c4741bce84d7ec2ad2

There should be a more robust implementation, though I am not sure how best to go about it.
