### ISSUE TITLE
Missing struct field if value is 0

### ISSUE THREAD

**Issue by karnauskas** [awslabs/goformation#181]
I see that some struct fields with 0 as value are not rendered in yaml or json. This is causing problems.

Eg in following code `DeviceIndex` is missing in final output.
```
...
import gcf "github.com/awslabs/goformation/cloudformation"
...
			NetworkInterfaces: []gcf.AWSEC2LaunchTemplate_NetworkInterface{
				gcf.AWSEC2LaunchTemplate_NetworkInterface{
					AssociatePublicIpAddress: true,
					DeviceIndex:              0,
					Groups: []string{
						gcf.Ref("SomeSg"),
					},
				},
			},
```
is rendered to in yaml:
```
        NetworkInterfaces:
        - AssociatePublicIpAddress: true
          Groups:
          - Ref: SomeSg
```
or json:
```
"NetworkInterfaces": [
            {
              "AssociatePublicIpAddress": true,
              "Groups": [
                {
                  "Ref": "SomeSg"
                }
              ]
            }
          ]
```
