### ISSUE TITLE
Serverless API Resource "Cors" property should be parseable as a string or a map

### ISSUE THREAD

**Issue by charlietran** [awslabs/goformation#244]
The SAM specification states that the "Cors" property of a Serverless API may be either a string or a Cors Configuration object (i.e. a `map[string]string in Go`)

<img width="846" alt="image" src="https://user-images.githubusercontent.com/659307/68534040-2097f600-02fe-11ea-83a6-02cc7587affc.png">

(screenshot from [SAM specification](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md))

Currently, GoFormation will throw a parsing error on a valid SAM `template.yml` if it has a Serverless API with Cors defined as an object, like so:
```yaml
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-rest-api"
      StageName: Prod
      TracingEnabled: false
      EndpointConfiguration: EDGE
      MethodSettings:
        - DataTraceEnabled: false
          HttpMethod: "*"
          LoggingLevel: ERROR
          MetricsEnabled: true
          ResourcePath: /*
      Cors:
        AllowHeaders: "'Authorization,authorization'"
        AllowOrigin: "'*'"
```
Parsing a template with this entry with `goformation.Open("template.yml")`will result in the error: 
```
ERROR: json: cannot unmarshal object into Go struct field Properties.Properties.Cors of type string
```

This is because the Cors property is defined to only be valid as a string: https://github.com/awslabs/goformation/blob/master/cloudformation/serverless/aws-serverless-api.go#L40-L43
cc @PaulMaddox
