### ISSUE TITLE
Add support for Intrinsic Functions in not string fields 

### ISSUE THREAD

**Issue by RafRabenda** [awslabs/goformation#252]
It should be a possibility to use Intrinsic Functions in any other field type than string, right now the following code, where "CreateDynamoBackUp" is condition in template, returns an error:

```
rootTemplate.Resources["DynamoDb"] = &dynamodb.Table{
    ...
    PointInTimeRecoverySpecification: &dynamodb.Table_PointInTimeRecoverySpecification{
        PointInTimeRecoveryEnabled: cloudformation.If("CreateDynamoBackUp", true, false),
   },
}
```
but is valid in the cloudformation, same with Equals or Ref functions:

```
  DynamoDbActivityTableName:
    Properties:
      ...
      PointInTimeRecoverySpecification:
         PointInTimeRecoveryEnabled:
            Fn::If:
            - CreateDynamoBackUp
            - true
            - false
    Type: AWS::SSM::::Table
```

Create a workaround for these cases is very time-consuming and generates much more maintenance work. When if field instead bool or int type was interface{}, go snippet would work
