### ISSUE TITLE
Transform schema is wrong, won't allow having multiple macros defined by returning nil

### ISSUE THREAD

**Issue by shivas** [awslabs/goformation#267]
Example templates:

```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  ExampleTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: example

Transform:
  - FirstMacro
  - SecondMacro
```

Above example returns Nil in Transform

Multiple transform macros are supported, details: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
