### ISSUE TITLE
goformation doesn't fail for invalid templates

### ISSUE THREAD

**Issue by sanathkr** [awslabs/goformation#27]
The following template is successfully parsed by goformation. It must fail:

```
Resources:
 ExampleFunction:
  Type: AWS::Serverless::Function
  Properties2**:
    Handler2: index.handler
    Runtime: nodejs6.10
    Events:
      Api:
        Type: Api
        iiProperties:
          Path: /
          Method: any 
```
