### ISSUE TITLE
Field Export in Struct Output needs to be a pointer for omitempty to take effect

### ISSUE THREAD

**Issue by paulbes** [awslabs/goformation#294]
The PR https://github.com/awslabs/goformation/pull/291 added a struct for the `Output`, but the `Export` field is not a pointer, this means that we will get the serialised name of the struct:

```yaml
Outputs:
  PrivateSubnetIds:
    Export: {} <------------ As so
    Value:
      Value:
        Fn::Join:
        - ','
        - - Ref: PrivateSubnet00
          - Ref: PrivateSubnet01
          - Ref: PrivateSubnet02
```

When validating this template with cloud formation we end up getting the following error message:
```text
ValidationError: Template format error: Output PrivateSubnetIds is malformed. The Name field of every Export member is required.
```

To fix this I believe that `Export` must be a pointer, reproduction:

```go
package main

import (
	"fmt"
	"encoding/json"
)

type A struct {
	B  B `json:",omitempty"`
	C *C `json:",omitempty"`
} 

type B struct {}

type C struct {}

func main() {
	d, _ := json.Marshal(&A{})
	fmt.Println(string(d))
}
```

This gives the following output:

```text
{"B":{}}
```

Note that `C` is omitted from the output.
