### ISSUE TITLE
Opening a template with NoProcess=true causes unmarshal error

### ISSUE THREAD

**Issue by Pheels** [awslabs/goformation#302]
My cloudformation template has the following:
```
Resources:
  ExampleFunction:    
    Type: AWS::Serverless::Function  
    Properties:  
      FunctionName: !Sub '${AWS::StackName}-ExampleFunction'
      CodeUri: ../build/example.zip
      Role: !GetAtt ExampleFunctionRole.arn
```

I am trying to marshal the template without processing the intrinsic functions.

I believe this is possibly by passing the NoProcessor option to the following function
https://github.com/awslabs/goformation/blob/master/goformation.go#L23

My code:
```
options := &intrinsics.ProcessorOptions{
  NoProcessor:true,
  EvalutateConditions:false,
  ProcessOnlyGlobals:false,
}; 

template, err := goformation.OpenWithOptions('mytemplate.yml', options);

```
This produces the following error:
```
ERROR: json: cannot unmarshal object into Go struct field Properties.Properties.FunctionName of type String
There was an error processing the template: json: cannot unmarshal object into Go struct field Template.Resources of type string
```

Apologies if i have missed something - there does not seem to be any documentation on this functionality.
