### ISSUE TITLE
examples for using intrinsic functions

### ISSUE THREAD

**Issue by iancoffey** [awslabs/goformation#31]
It would be great to have an example or two around building resources that make use of the [intrinsic](https://github.com/awslabs/goformation/tree/master/intrinsics) functions inside templates. The cloudformation package seems to have no concept of them. Im unclear how to achieve this, but perhaps Im missing something.

**Comment by pesama** [comment]
Hi Ian,

GoFormation currently uses intrinsic function resolution to resolve parameters present within the scope of the template. This allow GoFormation to be able to work with this template - excerpt:

```yaml
Parameters: 
  FunctionTimeout:
    Type: Number
    Default: 20
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Timeout: 
        Ref: MyFunctionTimeout
```

Can you please elaborate more on what you mean by _the cloudformation package seems to have no concept of them_? What would you like to see as an example?
