### ISSUE TITLE
Add support for AWS::CDK::Metadata Resource

### ISSUE THREAD

**Issue by jnsf-cg** [awslabs/goformation#334]
When attempting to Open a `json` or `yaml` file containing the contents outputted by the `cdk synth` command, an error is returned.

### Example Code

```go
	tpl, err := goformation.Open(filepath, nil)
	if err != nil {
		return "", fmt.Errorf("Unable to Open CF Template [%w]", err)
	}
```

### Example CF Template Content

```yaml
Resources:
  AppLBListener908F43BE:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - FixedResponseConfig:
            ContentType: text/plain
            MessageBody: Hello, world.
            StatusCode: "200"
          Type: fixed-response
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-FS-1-2-Res-2019-08
    Metadata:
      aws:cdk:path: Example1Stack/AppLB/Listener/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.73.0,@aws-cdk/assets=1.73.0,@aws-cdk/aws-cloudwatch=1.73.0,@aws-cdk/aws-ec2=1.73.0,@aws-cdk/aws-elasticloadbalancingv2=1.73.0,@aws-cdk/aws-events=1.73.0,@aws-cdk/aws-iam=1.73.0,@aws-cdk/aws-kms=1.73.0,@aws-cdk/aws-logs=1.73.0,@aws-cdk/aws-s3=1.73.0,@aws-cdk/aws-s3-assets=1.73.0,@aws-cdk/aws-ssm=1.73.0,@aws-cdk/cloud-assembly-schema=1.73.0,@aws-cdk/core=1.73.0,@aws-cdk/cx-api=1.73.0,@aws-cdk/region-info=1.73.0,jsii-runtime=node.js/v15.2.0
    Metadata:
      aws:cdk:path: Example1Stack/CDKMetadata/Default
```

### Expected

No error to be returned

### Got

Received the following error:

```
json: Unmarshal(nil)
```

Note: If I remove the `CDKMetadata` resource, the `Open(...)` succeeds.
