### ISSUE TITLE
Faill to parse the doc when Ref is a AWS::SSM::Parameter::Value<List<String>>

### ISSUE THREAD

**Issue by binchenX** [awslabs/goformation#395]
With following template file, the parse will fail with
```
 ERROR: json: cannot unmarshal string into Go struct field Properties.Properties.SubnetIds of type []string
2021/07/18 16:37:43 There was an error processing the template: json: cannot unmarshal string into Go struct field Template.Resources of type []string
```

 ```
 ---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: VPC Endpoints for Linux Custom ( STS )

  Parameters:
    VPCId:
      Description: VPC id of the account
      Type: AWS::EC2::VPC::Id

    VPCEndPointSubnets:
      Type: AWS::SSM::Parameter::Value<List<String>>
      Description: List of subnets for STS Private Endpoint
      Default: /CNS/resources/subnets/ic/all

  Resources:
    ecrApiVpcEndpoint:
      Type: "AWS::EC2::VPCEndpoint"
      Properties:
        ServiceName: "com.amazonaws.ap-southeast-2.ecr.api"
        VpcEndpointType: "Interface"
        VpcId: !Ref VPCId
        SubnetIds: !Ref VPCEndPointSubnets
        PrivateDnsEnabled: true
        SecurityGroupIds:
          - !Ref SGVPCEndPoint
```
