### ISSUE TITLE
SNS Event Source Properties are null when editing a sam template

### ISSUE THREAD

**Issue by billyshambrook** [awslabs/goformation#40]
I am using this library to read a SAM template, update the CodeUri for each function, and then render it back out.

Below is an example of what I am trying to do...

```
package main

import (
	"io/ioutil"
	"log"

	"github.com/awslabs/goformation"
	"github.com/awslabs/goformation/cloudformation"
)

const templateStr = `
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.6
      CodeUri: .
      Events:
        MyEvent:
          Type: SNS
          Properties:
            Topic: MyTopic
`

func main() {
	template, _ := goformation.ParseYAML([]byte(templateStr))
	functions := template.GetAllAWSServerlessFunctionResources()

	for name := range functions {
		function := functions[name]
		newPath := "somewhere"
		codeURI := cloudformation.AWSServerlessFunction_StringOrS3Location{String: &newPath}
		function.CodeUri = &codeURI

		template.Resources[name] = &function
	}

	y, err := template.YAML()
	if err != nil {
		log.Fatalf("Failed to generate YAML: %s\n", err)
	}

	newTemplate := "new-template.yaml"
	if err = ioutil.WriteFile(newTemplate, y, 0644); err != nil {
		log.Fatalf("Failed to create new-template.yaml: %s\n", err)
	}
}
```

When I run this, the SNS event properties value in new-template.yaml is `{}`...

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: somewhere
      Events:
        MyEvent:
          Properties: {}
          Type: SNS
      Handler: main.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
```
