### ISSUE TITLE
Expressing a typed array with optional parameters

### ISSUE THREAD

**Issue by ipmb** [awslabs/goformation#467]
How would I express a template like this (specifically the optional array item in `DomainValidationOptions`)?

The type is `[]certificatemanager.Certificate_DomainValidationOption`, but `cloudformation.If` returns a `string`

```yaml
---
Parameters:
  AltDomain1:
    AllowedPattern: "^[a-z0-9\\-\\.]*$"
    Default: ''
    Description: Alternate domain 1
    Type: String
Conditions:
  AltDomain1Exists:
    Fn::Not:
    - Fn::Equals:
      - Ref: AltDomain1
      - ''
Resources:
  Certificate:
    Properties:
      DomainName:
        Ref: PrimaryDomain
      DomainValidationOptions:
      - DomainName:
          Ref: PrimaryDomain
        HostedZoneId:
          Ref: HostedZone
      - Fn::If:
        - AltDomain1Exists
        - DomainName:
            Ref: AltDomain1
          HostedZoneId:
            Ref: HostedZone
        - Ref: AWS::NoValue
      SubjectAlternativeNames:
      - Fn::If:
        - AltDomain1Exists
        - Ref: AltDomain1
        - Ref: AWS::NoValue
      Tags:
      - Key: Name
        Value:
          Ref: PrimaryDomain
      ValidationMethod: DNS
    Type: AWS::CertificateManager::Certificate
```
