### ISSUE TITLE
Omnit value should be not included not be 0

### ISSUE THREAD

**Issue by xrn** [awslabs/goformation#474]
My code for `&opensearchservice.Domain{}` do not sets 

```
type Domain_SnapshotOptions struct {

	// AutomatedSnapshotStartHour AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-snapshotoptions.html#cfn-opensearchservice-domain-snapshotoptions-automatedsnapshotstarthour
	AutomatedSnapshotStartHour *int `json:"AutomatedSnapshotStartHour,omitempty"`
```

But generated yaml contains 

```
SnapshotOptions:
        AutomatedSnapshotStartHour: 0
```

Which is incorrect

**Comment by rubenfonseca** [comment]
Hi @xrn I tried to reproduce your code but with no success. Here's what I've tried:

```go
package main

import (
	"fmt"

	"github.com/awslabs/goformation/v6/cloudformation"
	"github.com/awslabs/goformation/v6/cloudformation/opensearchservice"
)

func main() {
	template := cloudformation.NewTemplate()
	template.Resources["MyResource"] = &opensearchservice.Domain{
		SnapshotOptions: &opensearchservice.Domain_SnapshotOptions{},
	}

	result, err := template.YAML()
	if err != nil {
		panic(err)
	}

	fmt.Println(string(result))
}
```

```YAML
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyResource:
    Properties:
      SnapshotOptions: {}
    Type: AWS::OpenSearchService::Domain
```

Can you please help us understand how to reproduce the bug?
