### ISSUE TITLE
Type detection for Default Parameters in Schema

### ISSUE THREAD

**Issue by sansmoraxz** [awslabs/goformation#497]
If we consider the below yaml sample snippet
```yaml
Parameters:
  EnabledPort:
    Type: Number
    Default: 22
```

As per the generated schema it's not valid as `Default` check's only registered for strings. Sure we can wrap it in quotes and call it a fix but it's logically incorrect as we are also explicitly telling it to be a number.
