### ISSUE TITLE
FunctionUrlConfig not defined in SAM schema

### ISSUE THREAD

**Issue by gmcquistin** [awslabs/goformation#561]
Given this SAM template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs18.x
      FunctionUrlConfig:
        AuthType: NONE
```

YAML Schema, via VS Code AWS Toolkit, reports the following:

```error
Property FunctionUrlConfig is not allowed. yaml-schema: aws://sam.schema.json
```

This property is documented[^1] but is defined in neither the AWS CloudFormation resource specification nor `sam.schema.json`.

Is it necessary to wait for the resource spec itself to be updated, or can the schema file in this repo be updated manually?

Thanks!

[^1]: https://docs.aws.amazon.com/lambda/latest/dg/API_FunctionUrlConfig.html
