### ISSUE TITLE
Missing property ReplicationGroupId for AWS::ElastiCache::ReplicationGroup

### ISSUE THREAD

**Issue by expe-elenigen** [awslabs/goformation#657]
The `AWS::ElastiCache::ReplicationGroup` type is missing the property `ReplicationGroupId` to configure the name of the cluster:
https://github.com/awslabs/goformation/blob/master/schema/cloudformation.schema.json

Even the AWS documentation is missing this value in the json and yaml list:

```yml
Type: AWS::ElastiCache::ReplicationGroup
Properties:
  AtRestEncryptionEnabled: Boolean
  AuthToken: String
  AutomaticFailoverEnabled: Boolean
  AutoMinorVersionUpgrade: Boolean
  CacheNodeType: String
  CacheParameterGroupName: String
  CacheSecurityGroupNames: 
    - String
  CacheSubnetGroupName: String
  ClusterMode: String
  DataTieringEnabled: Boolean
  Engine: String
  EngineVersion: String
  GlobalReplicationGroupId: String
  IpDiscovery: String
  KmsKeyId: String
  LogDeliveryConfigurations: 
    - LogDeliveryConfigurationRequest
  MultiAZEnabled: Boolean
  NetworkType: String
  NodeGroupConfiguration: 
    - NodeGroupConfiguration
  NotificationTopicArn: String
  NumCacheClusters: Integer
  NumNodeGroups: Integer
  Port: Integer
  PreferredCacheClusterAZs: 
    - String
  PreferredMaintenanceWindow: String
  PrimaryClusterId: String
  ReplicasPerNodeGroup: Integer
  ReplicationGroupDescription: String
  SecurityGroupIds: 
    - String
  SnapshotArns: 
    - String
  SnapshotName: String
  SnapshotRetentionLimit: Integer
  SnapshottingClusterId: String
  SnapshotWindow: String
  Tags: 
    - Tag
  TransitEncryptionEnabled: Boolean
  TransitEncryptionMode: String
  UserGroupIds: 
    - String
```

It should include 
```yml
  ReplicationGroupId: String
```
The `GlobalReplicationGroupId` is only for global clusters.

At the buttom of the page, there's still a mention of this property, but the description is missing:
```
ReplicationGroupId
Property description not available.
```
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html
