### ISSUE TITLE
SAM S3 filter rules schema incomplete

### ISSUE THREAD

**Issue by rgarcia** [awslabs/goformation#74]
The `S3Key` field on the [`AWSServerlessFunction_S3NotificationFilter`](https://godoc.org/github.com/awslabs/goformation/cloudformation#AWSServerlessFunction_S3NotificationFilter) type is a `string`, but in actual SAM templates it's an object with a `Rules` key containing an array of objects with `Name`/`Value`:

```yaml
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jpg'
```

The JSON schema files in this repo seem to reflect this correctly, so the problem may be with codegen?
