### ISSUE TITLE
Support for SSM Parameter Types

### ISSUE THREAD

**Issue by mkatrenik** [awslabs/goformation#89]
Would be nice to add https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types :-)

**Comment by notes-jj** [comment]
I use VS Code with Extension "YAML Support by Red Hat" (redhat.vscode-yaml).
It uses `schema/cloudformation.schema.json` from this project for validation.

Unfortunately the SSM Parameters are missing for Cloudformation Parameters Section.

The following cloudformation template will produce the error below.

**Cloudformation snippet**

```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KmsCmkKeyRegionArn:
    Description: KMS CMK Key from current Region
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /kms/eu-central-1/arn
```

**Error**

Value is not accepted. Valid values: "String", "Number", "List<Number>", "CommaDelimitedList", "AWS::EC2::AvailabilityZone::Name", "AWS::EC2::Image::Id", "AWS::EC2::Instance::Id", "AWS::EC2::KeyPair::KeyName", "AWS::EC2::SecurityGroup::GroupName", "AWS::EC2::SecurityGroup::Id", "AWS::EC2::Subnet::Id", "AWS::EC2::Volume::Id", "AWS::EC2::VPC::Id", "AWS::Route53::HostedZone::Id", "List<AWS::EC2::AvailabilityZone::Name>", "List<AWS::EC2::Image::Id>", "List<AWS::EC2::Instance::Id>", "List<AWS::EC2::SecurityGroup::GroupName>", "List<AWS::EC2::SecurityGroup::Id>", "List<AWS::EC2::Subnet::Id>", "List<AWS::EC2::Volume::Id>", "List<AWS::EC2::VPC::Id>", "List<AWS::Route53::HostedZone::Id>", "List<String>".
